name: test

on: [push,  pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: setting up execution
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
      - name: run
        run: npm install &&  npm test
