name: test

on: [push,  pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: setting up execution
    steps:
      uses: actions/checkout@v2
    - name: node setup
      uses: actions/setup-node@v1
      run: npm install &&  npm test
